---
root: true

plugins:
  - babel

env:
  node: true
  browser: true
  
parserOptions:
  ecmaVersion: latest
  sourceType: module

extends:
  - "airbnb-base"

rules:
  no-console: 0
  import/extensions: 0
